import { expect, test } from '@playwright/test'

test('Sprint 4 Crossref browser business flow', async ({ page }) => {
  const errors = []
  const directCrossref = []
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()) })
  page.on('pageerror', e => errors.push(e.message))
  page.on('request', r => { if (new URL(r.url()).hostname === 'api.crossref.org') directCrossref.push(r.url()) })
  page.on('dialog', dialog => dialog.dismiss())

  const suffix = `${Date.now()}`.slice(-8)+Math.random().toString(16).slice(2,6)
  const username = `xr${suffix}`
  const password = 'Crossref-123456'
  await page.goto('/register')
  const inputs = page.locator('input')
  await inputs.nth(0).fill(username)
  await inputs.nth(1).fill(`${username}@example.com`)
  await inputs.nth(2).fill(password)
  await inputs.nth(3).fill(password)
  await page.locator('.register-btn').click()
  await page.waitForURL('**/login')
  await page.locator('.login-form input').nth(0).fill(username)
  await page.locator('.login-form input').nth(1).fill(password)
  await page.locator('.login-btn').click()
  await page.waitForURL('**/papers')

  await page.goto('/discovery')
  await page.locator('.search-input').fill('retrieval augmented generation')
  const searchResponse = page.waitForResponse(r => new URL(r.url()).pathname === '/api/discovery/search')
  await page.locator('.search-btn').click()
  const response = await searchResponse
  expect(response.status()).toBe(200)
  const payload = await response.json()
  expect(payload.data.items.length).toBeGreaterThan(0)
  expect(payload.data.items[0].provider).toBe('crossref')
  expect(payload.data.items[0].doi).toContain('/')
  await expect(page.locator('.paper-item').first()).toBeVisible()
  await expect(page.locator('.paper-title').first()).not.toBeEmpty()

  const importResponse = page.waitForResponse(r => new URL(r.url()).pathname === '/api/discovery/import')
  await page.locator('.btn-import').first().click()
  expect((await importResponse).status()).toBe(200)
  await expect(page.locator('.btn-import').first()).toBeDisabled()
  const secondImport = page.waitForResponse(r => new URL(r.url()).pathname === '/api/discovery/import')
  await page.locator('.btn-import').nth(1).click()
  expect((await secondImport).status()).toBe(200)

  await page.goto('/recommendations')
  await page.locator('.el-select').first().click()
  await page.locator('.el-select-dropdown__item:visible').first().click()
  const byPaperResponse = page.waitForResponse(r => new URL(r.url()).pathname === '/api/recommendations/by-paper')
  await page.locator('.btn-generate').click()
  const byPaper = await (await byPaperResponse).json()
  expect(byPaper.data.length).toBeGreaterThan(0)
  await expect(page.locator('.results-list .paper-item').first()).toBeVisible()

  await page.locator('.mode-tab').nth(1).click()
  await page.locator('.el-select').first().click()
  const options = page.locator('.el-select-dropdown__item:visible')
  await options.nth(0).click()
  await page.locator('.el-select').first().click()
  await page.locator('.el-select-dropdown__item:visible').nth(1).click()
  const libraryResponse = page.waitForResponse(r => new URL(r.url()).pathname === '/api/recommendations/for-library')
  await page.locator('.btn-generate').click()
  const library = await (await libraryResponse).json()
  expect(library.data.length).toBeGreaterThan(0)
  await expect(page.locator('.score-tag').first()).toBeVisible()
  await expect(page.locator('.reason-tag').first()).toBeVisible()

  await page.locator('.mode-tab').nth(2).click()
  await page.locator('.topic-input').fill('retrieval augmented generation')
  const recResponse = page.waitForResponse(r => new URL(r.url()).pathname === '/api/recommendations/by-topic')
  await page.locator('.btn-generate').click()
  const rec = await (await recResponse).json()
  expect(rec.data.length).toBeGreaterThan(0)
  expect(rec.data.every(x => x.paper.provider === 'crossref' && x.is_fallback === false)).toBeTruthy()
  await expect(page.locator('.results-list .paper-item').first()).toBeVisible()
  await expect(page.locator('.score-tag').first()).toBeVisible()
  await expect(page.locator('.reason-tag').first()).toBeVisible()
  expect(rec.data.length).toBeGreaterThan(2)
  const importedTitle = rec.data[2].paper.title
  await page.locator('.paper-item').nth(0).locator('.btn-feedback').nth(0).click()
  await expect(page.locator('[data-testid=recommendation-status]').nth(0)).toHaveText('read_later')
  await page.locator('.paper-item').nth(1).locator('.btn-feedback').nth(1).click()
  await expect(page.locator('[data-testid=recommendation-status]').nth(1)).toHaveText('not_interested')
  await page.reload()
  await expect(page.locator('[data-testid=recommendation-status]').filter({ hasText: 'read_later' }).first()).toBeVisible()
  await expect(page.locator('[data-testid=recommendation-status]').filter({ hasText: 'not_interested' }).first()).toBeVisible()
  const importRecResponse = page.waitForResponse(r => /\/api\/recommendations\/\d+\/import$/.test(new URL(r.url()).pathname))
  await page.locator('.paper-item').filter({ hasText: importedTitle }).locator('.btn-import').click()
  expect((await importRecResponse).status()).toBe(200)
  await expect(page.locator('.paper-item').filter({ hasText: importedTitle }).locator('.btn-import')).toBeDisabled()
  await page.goto('/papers')
  await expect(page.locator('.paper-item').filter({ hasText: importedTitle })).toBeVisible()

  await page.goto('/graph')
  const enhanced = await page.evaluate(async () => {
    const token=localStorage.getItem('token')
    const r=await fetch('/api/graph/enhanced?include_external=true&max_nodes=50',{headers:{Authorization:`Bearer ${token}`}});return r.json()
  })
  expect(enhanced.code).toBe(200)
  expect(enhanced.data.nodes.length).toBeGreaterThan(0)
  expect(enhanced.data.nodes.every(n => typeof n.id === 'string')).toBeTruthy()

  expect(directCrossref).toEqual([])
  expect(errors).toEqual([])
  await expect(page.locator('.loading-state')).toHaveCount(0)
  console.log('SPRINT4_CROSSREF_BROWSER_E2E_OK')
})
